### importing libraries

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

## Loading data

In [2]:
data = pd.read_csv("property_sales_data.csv")
data.tail()

PropType      Taxkey             Address CondoProject  District  \
34518   Commercial  2420009000  4141 N RICHARDS ST          NaN         6   
34519  Vacant Land  2070279100   3202 W CAMERON AV          NaN         1   
34520  Vacant Land  6889973111      6154 S 13TH ST          NaN        13   
34521  Vacant Land  1120017000      7351 N BEAU AV          NaN         5   
34522  Vacant Land  3550447000   2208 N NEWHALL ST          NaN         3   

       Nbhd                         Style Extwall  Stories  Year_Built  \
34518  6236  Warehouse Building - 1 Story     NaN      1.0        1949   
34519  6232               Commercial Land     NaN      0.0           0   
34520  6290               Commercial Land     NaN      0.0           0   
34521   820                            **     NaN      0.0           0   
34522  3190                            **     NaN      0.0           0   

       Nr_of_rms  Fin_sqft  Units  Bdrms  Fbath  Hbath  Lotsize Sale_date  \
34518          0      4800      1      0      0      0     9000   2018-12   
34519          0         0      1      0      0      0     7800   2018-12   
34520          0         0      1      0      0      0   152286   2018-12   
34521          0         0      0      0      0      0     8925   2018-12   
34522          0         0      0      0      0      0     5400   2018-12   

       Sale_price  
34518      165000  
34519        3900  
34520      100000  
34521      362400  
34522       91000

In [3]:
data.nunique()

PropType            5
Taxkey          29439
Address         26846
CondoProject      537
District           15
Nbhd              591
Style             386
Extwall             9
Stories            19
Year_Built        168
Nr_of_rms          13
Fin_sqft         4421
Units               9
Bdrms              15
Fbath               8
Hbath               4
Lotsize          4740
Sale_date         204
Sale_price       3692
dtype: int64

In [4]:
# displaying specific row
data.iloc[95]

PropType                     Commercial
Taxkey                       3061230000
Address                5302 W CENTER ST
CondoProject                        NaN
District                             10
Nbhd                               6250
Style           Auto & Auto Body Repair
Extwall                             NaN
Stories                             1.0
Year_Built                         1929
Nr_of_rms                             0
Fin_sqft                           2057
Units                                 1
Bdrms                                 0
Fbath                                 0
Hbath                                 0
Lotsize                            5130
Sale_date                       2002-08
Sale_price                        34000
Name: 95, dtype: object

# LabelEncoding 

In [5]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
data["PropType"]  = label.fit_transform(data["PropType"])
data["PropType"]

0        0
1        0
2        0
3        0
4        0
        ..
34518    0
34519    4
34520    4
34521    4
34522    4
Name: PropType, Length: 34523, dtype: int32

 ## droping columns with null values except Proptype (y --->  independent variable)

In [6]:
data = data.dropna(subset = ["PropType"])
data.columns
#data.isnull().sum()

Index(['PropType', 'Taxkey', 'Address', 'CondoProject', 'District', 'Nbhd',
       'Style', 'Extwall', 'Stories', 'Year_Built', 'Nr_of_rms', 'Fin_sqft',
       'Units', 'Bdrms', 'Fbath', 'Hbath', 'Lotsize', 'Sale_date',
       'Sale_price'],
      dtype='object')

In [7]:
# from sklearn.impute import SimpleImputer
# sc = simpleImputer(strategy)
# data["PropType"] = sc.fit_transform()

In [8]:
data.isnull().sum()

PropType            0
Taxkey              0
Address             0
CondoProject    27867
District            0
Nbhd                0
Style               6
Extwall          9899
Stories             0
Year_Built          0
Nr_of_rms           0
Fin_sqft            0
Units               0
Bdrms               0
Fbath               0
Hbath               0
Lotsize             0
Sale_date           0
Sale_price          0
dtype: int64

In [9]:
data = data.dropna(axis = 1)


In [10]:
data.isnull().sum()

PropType      0
Taxkey        0
Address       0
District      0
Nbhd          0
Stories       0
Year_Built    0
Nr_of_rms     0
Fin_sqft      0
Units         0
Bdrms         0
Fbath         0
Hbath         0
Lotsize       0
Sale_date     0
Sale_price    0
dtype: int64

In [11]:
data.head()

PropType      Taxkey                  Address  District  Nbhd  Stories  \
0         0  3230461110            2628 N 6TH ST         6  6258      2.0   
1         0  3590192000       1363 N PROSPECT AV         3  6262      2.0   
2         0  4161194000            617 S 94TH ST        10  6272      1.0   
3         0  1719836000  3624 W SILVER SPRING DR         1  6218      2.0   
4         0  3480290000         3830 W LISBON AV        15  6254      2.0   

   Year_Built  Nr_of_rms  Fin_sqft  Units  Bdrms  Fbath  Hbath  Lotsize  \
0        1880          0      1840      1      0      0      0    12750   
1        1876          0      6377      1      0      0      0    11840   
2        1954          0      5022      1      0      0      0     9700   
3        1955          0      6420      1      0      0      0     8792   
4        1909          0      5956      1      0      0      0     4840   

  Sale_date  Sale_price  
0   2002-01       15900  
1   2002-01      850000  
2   2002-01      119000  
3   2002-01      210000  
4   2002-01       48500

In [12]:
data["Fin_sqft"].value_counts()

Fin_sqft
0        506
1056     133
980      133
864      130
936      124
        ... 
26550      1
7456       1
42389      1
2339       1
11462      1
Name: count, Length: 4421, dtype: int64

In [13]:
#data.columns[6]
data["Nr_of_rms"].value_counts()

Nr_of_rms
0     29052
4      2163
5      1545
3       913
6       503
2       108
7        90
1        84
8        48
10        7
9         5
11        3
12        2
Name: count, dtype: int64

In [14]:
#data = data.drop("Nr_of_rms",axis = 1)

In [15]:
data['Sale_date']

0        2002-01
1        2002-01
2        2002-01
3        2002-01
4        2002-01
          ...   
34518    2018-12
34519    2018-12
34520    2018-12
34521    2018-12
34522    2018-12
Name: Sale_date, Length: 34523, dtype: object

## converting date in string to date format and conveting to timestamp

In [16]:
data['Sale_date'] = pd.to_datetime(data['Sale_date'])
data

PropType      Taxkey                  Address  District  Nbhd  Stories  \
0             0  3230461110            2628 N 6TH ST         6  6258      2.0   
1             0  3590192000       1363 N PROSPECT AV         3  6262      2.0   
2             0  4161194000            617 S 94TH ST        10  6272      1.0   
3             0  1719836000  3624 W SILVER SPRING DR         1  6218      2.0   
4             0  3480290000         3830 W LISBON AV        15  6254      2.0   
...         ...         ...                      ...       ...   ...      ...   
34518         0  2420009000       4141 N RICHARDS ST         6  6236      1.0   
34519         4  2070279100        3202 W CAMERON AV         1  6232      0.0   
34520         4  6889973111           6154 S 13TH ST        13  6290      0.0   
34521         4  1120017000           7351 N BEAU AV         5   820      0.0   
34522         4  3550447000        2208 N NEWHALL ST         3  3190      0.0   

       Year_Built  Nr_of_rms  Fin_sqft  Units  Bdrms  Fbath  Hbath  Lotsize  \
0            1880          0      1840      1      0      0      0    12750   
1            1876          0      6377      1      0      0      0    11840   
2            1954          0      5022      1      0      0      0     9700   
3            1955          0      6420      1      0      0      0     8792   
4            1909          0      5956      1      0      0      0     4840   
...           ...        ...       ...    ...    ...    ...    ...      ...   
34518        1949          0      4800      1      0      0      0     9000   
34519           0          0         0      1      0      0      0     7800   
34520           0          0         0      1      0      0      0   152286   
34521           0          0         0      0      0      0      0     8925   
34522           0          0         0      0      0      0      0     5400   

       Sale_date  Sale_price  
0     2002-01-01       15900  
1     2002-01-01      850000  
2     2002-01-01      119000  
3     2002-01-01      210000  
4     2002-01-01       48500  
...          ...         ...  
34518 2018-12-01      165000  
34519 2018-12-01        3900  
34520 2018-12-01      100000  
34521 2018-12-01      362400  
34522 2018-12-01       91000  

[34523 rows x 16 columns]

In [17]:
data['Sale_date'] = pd.to_datetime(data['Sale_date'])
data['timestamp'] = data['Sale_date'].apply(lambda x: x.timestamp())
data.drop('Sale_date',axis = 1,inplace = True)
data.head(5)

PropType      Taxkey                  Address  District  Nbhd  Stories  \
0         0  3230461110            2628 N 6TH ST         6  6258      2.0   
1         0  3590192000       1363 N PROSPECT AV         3  6262      2.0   
2         0  4161194000            617 S 94TH ST        10  6272      1.0   
3         0  1719836000  3624 W SILVER SPRING DR         1  6218      2.0   
4         0  3480290000         3830 W LISBON AV        15  6254      2.0   

   Year_Built  Nr_of_rms  Fin_sqft  Units  Bdrms  Fbath  Hbath  Lotsize  \
0        1880          0      1840      1      0      0      0    12750   
1        1876          0      6377      1      0      0      0    11840   
2        1954          0      5022      1      0      0      0     9700   
3        1955          0      6420      1      0      0      0     8792   
4        1909          0      5956      1      0      0      0     4840   

   Sale_price     timestamp  
0       15900  1.009843e+09  
1      850000  1.009843e+09  
2      119000  1.009843e+09  
3      210000  1.009843e+09  
4       48500  1.009843e+09

In [18]:
col_to_move = data.pop('Sale_price')
data['Sale_price'] = col_to_move
# pos = len(data.columns) -1 
# data.insert(pos,'Sale_price',col_to_move)
data

PropType      Taxkey                  Address  District  Nbhd  Stories  \
0             0  3230461110            2628 N 6TH ST         6  6258      2.0   
1             0  3590192000       1363 N PROSPECT AV         3  6262      2.0   
2             0  4161194000            617 S 94TH ST        10  6272      1.0   
3             0  1719836000  3624 W SILVER SPRING DR         1  6218      2.0   
4             0  3480290000         3830 W LISBON AV        15  6254      2.0   
...         ...         ...                      ...       ...   ...      ...   
34518         0  2420009000       4141 N RICHARDS ST         6  6236      1.0   
34519         4  2070279100        3202 W CAMERON AV         1  6232      0.0   
34520         4  6889973111           6154 S 13TH ST        13  6290      0.0   
34521         4  1120017000           7351 N BEAU AV         5   820      0.0   
34522         4  3550447000        2208 N NEWHALL ST         3  3190      0.0   

       Year_Built  Nr_of_rms  Fin_sqft  Units  Bdrms  Fbath  Hbath  Lotsize  \
0            1880          0      1840      1      0      0      0    12750   
1            1876          0      6377      1      0      0      0    11840   
2            1954          0      5022      1      0      0      0     9700   
3            1955          0      6420      1      0      0      0     8792   
4            1909          0      5956      1      0      0      0     4840   
...           ...        ...       ...    ...    ...    ...    ...      ...   
34518        1949          0      4800      1      0      0      0     9000   
34519           0          0         0      1      0      0      0     7800   
34520           0          0         0      1      0      0      0   152286   
34521           0          0         0      0      0      0      0     8925   
34522           0          0         0      0      0      0      0     5400   

          timestamp  Sale_price  
0      1.009843e+09       15900  
1      1.009843e+09      850000  
2      1.009843e+09      119000  
3      1.009843e+09      210000  
4      1.009843e+09       48500  
...             ...         ...  
34518  1.543622e+09      165000  
34519  1.543622e+09        3900  
34520  1.543622e+09      100000  
34521  1.543622e+09      362400  
34522  1.543622e+09       91000  

[34523 rows x 16 columns]

In [52]:
#data['PropType'].nunique()
data.head()

PropType      Taxkey                  Address  District  Nbhd  Stories  \
0         0  3230461110            2628 N 6TH ST         6  6258      2.0   
1         0  3590192000       1363 N PROSPECT AV         3  6262      2.0   
2         0  4161194000            617 S 94TH ST        10  6272      1.0   
3         0  1719836000  3624 W SILVER SPRING DR         1  6218      2.0   
4         0  3480290000         3830 W LISBON AV        15  6254      2.0   

   Year_Built  Nr_of_rms  Fin_sqft  Units  Bdrms  Fbath  Hbath  Lotsize  \
0        1880          0      1840      1      0      0      0    12750   
1        1876          0      6377      1      0      0      0    11840   
2        1954          0      5022      1      0      0      0     9700   
3        1955          0      6420      1      0      0      0     8792   
4        1909          0      5956      1      0      0      0     4840   

      timestamp  Sale_price  
0  1.009843e+09       15900  
1  1.009843e+09      850000  
2  1.009843e+09      119000  
3  1.009843e+09      210000  
4  1.009843e+09       48500

## independent variables 

In [53]:
#x = data[["Nbhd","Stories","Year_Built",'Fin_sqft',"Units","Lotsize"]]
xc = data[['Nr_of_rms','Units','Bdrms','Fbath','Hbath','Lotsize']]
xr = data[['District','Stories','Nr_of_rms','Fin_sqft','Units','Bdrms','Fbath','Hbath','Lotsize']]

xc.columns

Index(['Nr_of_rms', 'Units', 'Bdrms', 'Fbath', 'Hbath', 'Lotsize'], dtype='object')

## dependent variable

In [54]:
y_classify = data["PropType"] 

In [55]:
y_reg = data['Sale_price']

## splitting train and test split data

In [56]:
from sklearn.model_selection import train_test_split
x_train_c,x_test_c,y_train_c,y_test_c = train_test_split(xc,y_classify,test_size = .2,random_state = 2)
x_train_r,x_test_r,y_train_r,y_test_r = train_test_split(xr,y_reg,test_size = .2, random_state = 0)

## standardization

In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_c = sc.fit_transform(x_train_c)
x_test_c = sc.fit_transform(x_test_c)
x_train_r = sc.fit_transform(x_train_r)
x_test_r = sc.fit_transform(x_test_r)

In [58]:
x_test_c

array([[-0.40296595, -0.34801762,  0.17273552, -0.40450038,  1.36631106,
        -0.10113917],
       [-0.40296595, -0.34801762, -1.82850401, -1.73263881, -0.60575789,
         0.80601123],
       [-0.40296595,  2.09411824,  2.17397505,  2.25177648, -0.60575789,
        -0.16258789],
       ...,
       [-0.40296595, -2.79015349, -1.82850401, -1.73263881, -0.60575789,
         0.06003706],
       [-0.40296595, -0.34801762,  0.17273552, -0.40450038, -0.60575789,
        -0.11501469],
       [-0.40296595, -0.34801762, -0.49434432, -0.40450038,  1.36631106,
        -0.09915696]])

In [59]:
y_train_c
y_train_r

25246     16000
12656    105000
3421      75000
16860     94000
29145     34900
          ...  
20757     47000
32103    122000
30403    135000
21243    199900
2732     179000
Name: Sale_price, Length: 27618, dtype: int64

## classification model 

In [60]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train_c,y_train_c)

RandomForestClassifier()

In [61]:
y_pred_c = model.predict(x_test_c)
y_pred_c


array([3, 2, 3, ..., 4, 3, 3])

0.9588703837798697

In [63]:
xc

Nr_of_rms  Units  Bdrms  Fbath  Hbath  Lotsize
0              0      1      0      0      0    12750
1              0      1      0      0      0    11840
2              0      1      0      0      0     9700
3              0      1      0      0      0     8792
4              0      1      0      0      0     4840
...          ...    ...    ...    ...    ...      ...
34518          0      1      0      0      0     9000
34519          0      1      0      0      0     7800
34520          0      1      0      0      0   152286
34521          0      0      0      0      0     8925
34522          0      0      0      0      0     5400

[34523 rows x 6 columns]

In [64]:
ic=[[0,1,2,1,1,15000]]
scaled_calInput = sc.fit_transform(ic)
scaled_calInput = pd.DataFrame(scaled_calInput)
output = model.predict(scaled_calInput)
output

array([3])

In [65]:
## Regression model

In [66]:
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor()
reg.fit(x_train_r,y_train_r)

RandomForestRegressor()

In [67]:
y_pred_r = reg.predict(x_test_r)
y_pred_r

array([ 191476.16666667,  143282.5       ,  174591.66666667, ...,
        315072.28666667,  252160.66666667, 1224893.16666667])

In [68]:
from sklearn.metrics import (
mean_squared_error,
mean_absolute_error,
r2_score,
explained_variance_score
)
mse_r = mean_squared_error(y_test_r,y_pred_r)
mse_r
# mae_r = mean_absolute_error(y_test_r,y_pred_r)
# mae_r

309923466886.6182

In [69]:
r2=r2_score(y_test_r,y_pred_r)
r2

0.6389661893784542

In [72]:
# xr = data[['District','Stories','Nr_of_rms','Fin_sqft','Units','Bdrms','Fbath','Hbath','Lotsize']]
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
regression_input = [[6,2.0,2,6258,1,1,0,1,9700]]
scaled_regInput = sc.fit_transform(regression_input)
scaled_regInput = pd.DataFrame(scaled_regInput)
scaled_regInput

0    1    2    3    4    5    6    7    8
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [73]:
output = reg.predict(scaled_regInput)
output

array([182158.5])

# linearregression


In [40]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()


In [42]:
model.fit(x_train_r,y_train_r)

LinearRegression()

In [43]:
y_pred_r = reg.predict(x_test_r)


In [44]:
r2=r2_score(y_test_r,y_pred_r)
r2

0.5772525051116314

In [45]:
mse=mean_squared_error(y_test_r,y_pred_r)
mse

362900552188.9399